/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // General Basic
  DSA: [
    {
      type: 'autogenerated',
      dirName: 'General_Basic/DSA',
    }
  ],
  x86_64_AS: [
    {
      type: 'autogenerated',
      dirName: 'General_Basic/Assembly/x86_64'
    }
  ],
  CO: [
    {
      type: 'autogenerated',
      dirName: 'General_Basic/Computer_Organization'
    }
  ],
  OS: [
    {
      type: 'autogenerated',
      dirName: 'General_Basic/Computer_OS'
    }
  ],
  NetWork: [
    {
      type: 'autogenerated',
      dirName: 'General_Basic/Computer_Network'
    }
  ],

  // C&C++
  C: [
    {
      type: 'autogenerated',
      dirName: 'C&CPP/Languages/C'
    }
  ],
  CPP: [
    {
      type: 'autogenerated',
      dirName: 'C&CPP/Languages/CPP'
    }
  ],
  CMake: [
    {
      type: 'autogenerated',
      dirName: 'C&CPP/Tools/CMake'
    }
  ],

  // Python
  Python: [
    {
      type: 'autogenerated',
      dirName: 'Python/Languages/Python'
    },
  ],

  // Web App
  HTML: [
    {
      type: 'autogenerated',
      dirName: 'WebAPP/Language_Basics/HTML',
    },
  ],
  CSS: [
    {
      type: 'autogenerated',
      dirName: 'WebAPP/Language_Basics/CSS',
    },
  ],
  JS: [
    {
      type: 'autogenerated',
      dirName: 'WebAPP/Language_Basics/JavaScript',
    },
  ],
};

export default sidebars;
